"use client";

import React from "react";
import Link from "next/link";
import { Scale, ArrowLeft, AlertCircle, FileText, Activity, ShieldAlert } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-6 md:p-12 font-sans relative overflow-hidden">
      {/* Background Decor */}
      <div className="absolute top-0 left-0 w-[500px] h-[500px] bg-emerald-600/10 blur-[120px] rounded-full -z-10 pointer-events-none" />
      <div className="absolute bottom-0 right-0 w-[500px] h-[500px] bg-indigo-600/5 blur-[120px] rounded-full -z-10 pointer-events-none" />

      <div className="max-w-4xl mx-auto space-y-12">
        <header className="space-y-4">
          <Link href="/">
            <Button variant="ghost" className="text-slate-400 hover:text-white -ml-4">
              <ArrowLeft className="w-4 h-4 mr-2" /> Back to Aegis
            </Button>
          </Link>
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 bg-emerald-600/20 border border-emerald-500/30 rounded-2xl flex items-center justify-center">
              <Scale className="w-6 h-6 text-emerald-400" />
            </div>
            <h1 className="text-4xl font-extrabold tracking-tighter">Terms of Service</h1>
          </div>
          <p className="text-slate-400 font-mono text-sm uppercase tracking-widest">
            Revision: 2026.1 // Clinical AI Deployment Protocol
          </p>
        </header>

        <section className="space-y-12">
          {/* Critical Disclaimer */}
          <div className="p-8 rounded-3xl border border-red-500/20 bg-red-500/5 space-y-4 shadow-[0_0_30px_rgba(239,68,68,0.1)]">
            <div className="flex items-center gap-3 text-red-400">
              <ShieldAlert className="w-6 h-6" />
              <h2 className="text-xl font-bold uppercase tracking-tight">Emergency Warning</h2>
            </div>
            <p className="text-sm text-red-200/80 leading-relaxed">
              Aegis Triage OS is NOT an emergency response system. If you are experiencing a life-threatening medical emergency (e.g., chest pain, difficulty breathing, severe bleeding, or stroke symptoms), call your local emergency number (e.g., 102/108) IMMEDIATELY.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
            <div className="space-y-6">
              <div className="space-y-4">
                <h3 className="text-xl font-bold flex items-center gap-2">
                  <Activity className="w-5 h-5 text-indigo-400" /> 1. Nature of Service
                </h3>
                <p className="text-sm text-slate-400 leading-relaxed">
                  Aegis provides AI-assisted clinical decision support (CDSS). The outputs generated by our algorithms are guidance for prioritization and are not licensed medical diagnoses.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-xl font-bold flex items-center gap-2">
                  <FileText className="w-5 h-5 text-emerald-400" /> 2. Clinical Use
                </h3>
                <p className="text-sm text-slate-400 leading-relaxed">
                  Clinician dashboards are for use by licensed medical professionals only. Unauthorized access to clinical queues is a violation of these terms and may be subject to legal action under healthcare privacy laws.
                </p>
              </div>
            </div>

            <div className="space-y-6">
              <div className="space-y-4">
                <h3 className="text-xl font-bold flex items-center gap-2">
                  <AlertCircle className="w-5 h-5 text-amber-400" /> 3. Data Integrity
                </h3>
                <p className="text-sm text-slate-400 leading-relaxed">
                  Users are responsible for the accuracy of information provided during triage. Inaccurate symptom reporting may lead to incorrect care-level recommendations.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-xl font-bold flex items-center gap-2">
                  <Scale className="w-5 h-5 text-indigo-400" /> 4. Limitation of Liability
                </h3>
                <p className="text-sm text-slate-400 leading-relaxed">
                  Aegis Triage OS and its developers are not liable for any clinical outcomes resulting from the use of the triage guidance. Final clinical decisions must be made by a human physician.
                </p>
              </div>
            </div>
          </div>
        </section>

        <footer className="pt-12 border-t border-white/5 flex flex-col md:flex-row justify-between gap-4 items-center text-slate-500 text-xs font-mono">
          <p>© 2026 Aegis Triage OS // Zero-Trust Clinical Architecture</p>
          <div className="flex gap-6">
            <Link href="/privacy" className="hover:text-indigo-400 transition-colors">Privacy Policy</Link>
            <a href="mailto:compliance@aegis.local" className="hover:text-indigo-400 transition-colors">Compliance Contact</a>
          </div>
        </footer>
      </div>
    </div>
  );
}
